export interface Country {
    name: string;
    code: string;
    dial_code: string;
    flag: string;
}

export const countries: Country[] = [
    { name: "Afeganistão", code: "AF", dial_code: "+93", flag: "🇦🇫" },
    { name: "África do Sul", code: "ZA", dial_code: "+27", flag: "🇿🇦" },
    { name: "Albânia", code: "AL", dial_code: "+355", flag: "🇦🇱" },
    { name: "Alemanha", code: "DE", dial_code: "+49", flag: "🇩🇪" },
    { name: "Andorra", code: "AD", dial_code: "+376", flag: "🇦🇩" },
    { name: "Angola", code: "AO", dial_code: "+244", flag: "🇦🇴" },
    { name: "Arábia Saudita", code: "SA", dial_code: "+966", flag: "🇸🇦" },
    { name: "Argélia", code: "DZ", dial_code: "+213", flag: "🇩🇿" },
    { name: "Argentina", code: "AR", dial_code: "+54", flag: "🇦🇷" },
    { name: "Armênia", code: "AM", dial_code: "+374", flag: "🇦🇲" },
    { name: "Austrália", code: "AU", dial_code: "+61", flag: "🇦🇺" },
    { name: "Áustria", code: "AT", dial_code: "+43", flag: "🇦🇹" },
    { name: "Azerbaijão", code: "AZ", dial_code: "+994", flag: "🇦🇿" },
    { name: "Bahamas", code: "BS", dial_code: "+1", flag: "🇧🇸" },
    { name: "Bangladesh", code: "BD", dial_code: "+880", flag: "🇧🇩" },
    { name: "Barbados", code: "BB", dial_code: "+1", flag: "🇧🇧" },
    { name: "Bahrein", code: "BH", dial_code: "+973", flag: "🇧🇭" },
    { name: "Bélgica", code: "BE", dial_code: "+32", flag: "🇧🇪" },
    { name: "Belize", code: "BZ", dial_code: "+501", flag: "🇧🇿" },
    { name: "Benin", code: "BJ", dial_code: "+229", flag: "🇧🇯" },
    { name: "Bielorrússia", code: "BY", dial_code: "+375", flag: "🇧🇾" },
    { name: "Bolívia", code: "BO", dial_code: "+591", flag: "🇧🇴" },
    { name: "Bósnia e Herzegovina", code: "BA", dial_code: "+387", flag: "🇧🇦" },
    { name: "Botsuana", code: "BW", dial_code: "+267", flag: "🇧🇼" },
    { name: "Brasil", code: "BR", dial_code: "+55", flag: "🇧🇷" },
    { name: "Brunei", code: "BN", dial_code: "+673", flag: "🇧🇳" },
    { name: "Bulgária", code: "BG", dial_code: "+359", flag: "🇧🇬" },
    { name: "Burkina Faso", code: "BF", dial_code: "+226", flag: "🇧🇫" },
    { name: "Burundi", code: "BI", dial_code: "+257", flag: "🇧🇮" },
    { name: "Cabo Verde", code: "CV", dial_code: "+238", flag: "🇨🇻" },
    { name: "Camarões", code: "CM", dial_code: "+237", flag: "🇨🇲" },
    { name: "Camboja", code: "KH", dial_code: "+855", flag: "🇰🇭" },
    { name: "Canadá", code: "CA", dial_code: "+1", flag: "🇨🇦" },
    { name: "Catar", code: "QA", dial_code: "+974", flag: "🇶🇦" },
    { name: "Cazaquistão", code: "KZ", dial_code: "+7", flag: "🇰🇿" },
    { name: "Chade", code: "TD", dial_code: "+235", flag: "🇹🇩" },
    { name: "Chile", code: "CL", dial_code: "+56", flag: "🇨🇱" },
    { name: "China", code: "CN", dial_code: "+86", flag: "🇨🇳" },
    { name: "Chipre", code: "CY", dial_code: "+357", flag: "🇨🇾" },
    { name: "Colômbia", code: "CO", dial_code: "+57", flag: "🇨🇴" },
    { name: "Comores", code: "KM", dial_code: "+269", flag: "🇰🇲" },
    { name: "Congo", code: "CG", dial_code: "+242", flag: "🇨🇬" },
    { name: "Coreia do Norte", code: "KP", dial_code: "+850", flag: "🇰🇵" },
    { name: "Coreia do Sul", code: "KR", dial_code: "+82", flag: "🇰🇷" },
    { name: "Costa Rica", code: "CR", dial_code: "+506", flag: "🇨🇷" },
    { name: "Croácia", code: "HR", dial_code: "+385", flag: "🇭🇷" },
    { name: "Cuba", code: "CU", dial_code: "+53", flag: "🇨🇺" },
    { name: "Dinamarca", code: "DK", dial_code: "+45", flag: "🇩🇰" },
    { name: "Djibuti", code: "DJ", dial_code: "+253", flag: "🇩🇯" },
    { name: "Dominica", code: "DM", dial_code: "+1", flag: "🇩🇲" },
    { name: "Egito", code: "EG", dial_code: "+20", flag: "🇪🇬" },
    { name: "El Salvador", code: "SV", dial_code: "+503", flag: "🇸🇻" },
    { name: "Emirados Árabes Unidos", code: "AE", dial_code: "+971", flag: "🇦🇪" },
    { name: "Equador", code: "EC", dial_code: "+593", flag: "🇪🇨" },
    { name: "Eritreia", code: "ER", dial_code: "+291", flag: "🇪🇷" },
    { name: "Eslováquia", code: "SK", dial_code: "+421", flag: "🇸🇰" },
    { name: "Eslovênia", code: "SI", dial_code: "+386", flag: "🇸🇮" },
    { name: "Espanha", code: "ES", dial_code: "+34", flag: "🇪🇸" },
    { name: "Estados Unidos", code: "US", dial_code: "+1", flag: "🇺🇸" },
    { name: "Estônia", code: "EE", dial_code: "+372", flag: "🇪🇪" },
    { name: "Etiópia", code: "ET", dial_code: "+251", flag: "🇪🇹" },
    { name: "Fiji", code: "FJ", dial_code: "+679", flag: "🇫🇯" },
    { name: "Filipinas", code: "PH", dial_code: "+63", flag: "🇵🇭" },
    { name: "Finlândia", code: "FI", dial_code: "+358", flag: "🇫🇮" },
    { name: "França", code: "FR", dial_code: "+33", flag: "🇫🇷" },
    { name: "Gabão", code: "GA", dial_code: "+241", flag: "🇬🇦" },
    { name: "Gâmbia", code: "GM", dial_code: "+220", flag: "🇬🇲" },
    { name: "Gana", code: "GH", dial_code: "+233", flag: "🇬🇭" },
    { name: "Geórgia", code: "GE", dial_code: "+995", flag: "🇬🇪" },
    { name: "Granada", code: "GD", dial_code: "+1", flag: "🇬🇩" },
    { name: "Grécia", code: "GR", dial_code: "+30", flag: "🇬🇷" },
    { name: "Guatemala", code: "GT", dial_code: "+502", flag: "🇬🇹" },
    { name: "Guiana", code: "GY", dial_code: "+592", flag: "🇬🇾" },
    { name: "Guiné", code: "GN", dial_code: "+224", flag: "🇬🇳" },
    { name: "Guiné-Bissau", code: "GW", dial_code: "+245", flag: "🇬🇼" },
    { name: "Guiné Equatorial", code: "GQ", dial_code: "+240", flag: "🇬🇶" },
    { name: "Haiti", code: "HT", dial_code: "+509", flag: "🇭🇹" },
    { name: "Holanda", code: "NL", dial_code: "+31", flag: "🇳🇱" },
    { name: "Honduras", code: "HN", dial_code: "+504", flag: "🇭🇳" },
    { name: "Hungria", code: "HU", dial_code: "+36", flag: "🇭🇺" },
    { name: "Iêmen", code: "YE", dial_code: "+967", flag: "🇾🇪" },
    { name: "Ilhas Fiji", code: "FJ", dial_code: "+679", flag: "🇫🇯" },
    { name: "Índia", code: "IN", dial_code: "+91", flag: "🇮🇳" },
    { name: "Indonésia", code: "ID", dial_code: "+62", flag: "🇮🇩" },
    { name: "Irã", code: "IR", dial_code: "+98", flag: "🇮🇷" },
    { name: "Iraque", code: "IQ", dial_code: "+964", flag: "🇮🇶" },
    { name: "Irlanda", code: "IE", dial_code: "+353", flag: "🇮🇪" },
    { name: "Islândia", code: "IS", dial_code: "+354", flag: "🇮🇸" },
    { name: "Israel", code: "IL", dial_code: "+972", flag: "🇮🇱" },
    { name: "Itália", code: "IT", dial_code: "+39", flag: "🇮🇹" },
    { name: "Jamaica", code: "JM", dial_code: "+1", flag: "🇯🇲" },
    { name: "Japão", code: "JP", dial_code: "+81", flag: "🇯🇵" },
    { name: "Jordânia", code: "JO", dial_code: "+962", flag: "🇯🇴" },
    { name: "Kuwait", code: "KW", dial_code: "+965", flag: "🇰🇼" },
    { name: "Laos", code: "LA", dial_code: "+856", flag: "🇱🇦" },
    { name: "Letônia", code: "LV", dial_code: "+371", flag: "🇱🇻" },
    { name: "Líbano", code: "LB", dial_code: "+961", flag: "🇱🇧" },
    { name: "Líbia", code: "LY", dial_code: "+218", flag: "🇱🇾" },
    { name: "Liechtenstein", code: "LI", dial_code: "+423", flag: "🇱🇮" },
    { name: "Lituânia", code: "LT", dial_code: "+370", flag: "🇱🇹" },
    { name: "Luxemburgo", code: "LU", dial_code: "+352", flag: "🇱🇺" },
    { name: "Malásia", code: "MY", dial_code: "+60", flag: "🇲🇾" },
    { name: "Maldivas", code: "MV", dial_code: "+960", flag: "🇲🇻" },
    { name: "Mali", code: "ML", dial_code: "+223", flag: "🇲🇱" },
    { name: "Malta", code: "MT", dial_code: "+356", flag: "🇲🇹" },
    { name: "Marrocos", code: "MA", dial_code: "+212", flag: "🇲🇦" },
    { name: "México", code: "MX", dial_code: "+52", flag: "🇲🇽" },
    { name: "Mônaco", code: "MC", dial_code: "+377", flag: "🇲🇨" },
    { name: "Mongólia", code: "MN", dial_code: "+976", flag: "🇲🇳" },
    { name: "Montenegro", code: "ME", dial_code: "+382", flag: "🇲🇪" },
    { name: "Moçambique", code: "MZ", dial_code: "+258", flag: "🇲" },
    { name: "Namíbia", code: "NA", dial_code: "+264", flag: "🇳🇦" },
    { name: "Nepal", code: "NP", dial_code: "+977", flag: "🇳🇵" },
    { name: "Nicarágua", code: "NI", dial_code: "+505", flag: "🇳🇮" },
    { name: "Níger", code: "NE", dial_code: "+227", flag: "🇳🇪" },
    { name: "Nigéria", code: "NG", dial_code: "+234", flag: "🇳🇬" },
    { name: "Noruega", code: "NO", dial_code: "+47", flag: "🇳🇴" },
    { name: "Nova Zelândia", code: "NZ", dial_code: "+64", flag: "🇳🇿" },
    { name: "Omã", code: "OM", dial_code: "+968", flag: "🇴🇲" },
    { name: "Panamá", code: "PA", dial_code: "+507", flag: "🇵🇦" },
    { name: "Paquistão", code: "PK", dial_code: "+92", flag: "🇵🇰" },
    { name: "Paraguai", code: "PY", dial_code: "+595", flag: "🇵🇾" },
    { name: "Peru", code: "PE", dial_code: "+51", flag: "🇵🇪" },
    { name: "Polônia", code: "PL", dial_code: "+48", flag: "🇵🇱" },
    { name: "Portugal", code: "PT", dial_code: "+351", flag: "🇵🇹" },
    { name: "Quênia", code: "KE", dial_code: "+254", flag: "🇰🇪" },
    { name: "Reino Unido", code: "GB", dial_code: "+44", flag: "🇬🇧" },
    { name: "República Centro-Africana", code: "CF", dial_code: "+236", flag: "🇨🇫" },
    { name: "República Checa", code: "CZ", dial_code: "+420", flag: "🇨🇿" },
    { name: "Rep. Dem. do Congo", code: "CD", dial_code: "+243", flag: "🇨🇩" },
    { name: "República Dominicana", code: "DO", dial_code: "+1", flag: "🇩🇴" },
    { name: "Romênia", code: "RO", dial_code: "+40", flag: "🇷🇴" },
    { name: "Rússia", code: "RU", dial_code: "+7", flag: "🇷🇺" },
    { name: "Senegal", code: "SN", dial_code: "+221", flag: "🇸🇳" },
    { name: "Serra Leoa", code: "SL", dial_code: "+232", flag: "🇸🇱" },
    { name: "Sérvia", code: "RS", dial_code: "+381", flag: "🇷🇸" },
    { name: "Singapura", code: "SG", dial_code: "+65", flag: "🇸🇬" },
    { name: "Síria", code: "SY", dial_code: "+963", flag: "🇸🇾" },
    { name: "Somália", code: "SO", dial_code: "+252", flag: "🇸🇴" },
    { name: "Sri Lanka", code: "LK", dial_code: "+94", flag: "🇱🇰" },
    { name: "Suazilândia", code: "SZ", dial_code: "+268", flag: "🇸🇿" },
    { name: "Sudão", code: "SD", dial_code: "+249", flag: "🇸🇩" },
    { name: "Suécia", code: "SE", dial_code: "+46", flag: "🇸🇪" },
    { name: "Suíça", code: "CH", dial_code: "+41", flag: "🇨🇭" },
    { name: "Tailândia", code: "TH", dial_code: "+66", flag: "🇹🇭" },
    { name: "Taiwan", code: "TW", dial_code: "+886", flag: "🇹🇼" },
    { name: "Timor-Leste", code: "TL", dial_code: "+670", flag: "🇹🇱" },
    { name: "Togo", code: "TG", dial_code: "+228", flag: "🇹🇬" },
    { name: "Tunísia", code: "TN", dial_code: "+216", flag: "🇹🇳" },
    { name: "Turquia", code: "TR", dial_code: "+90", flag: "🇹🇷" },
    { name: "Ucrânia", code: "UA", dial_code: "+380", flag: "🇺🇦" },
    { name: "Uganda", code: "UG", dial_code: "+256", flag: "🇺🇬" },
    { name: "Uruguai", code: "UY", dial_code: "+598", flag: "🇺🇾" },
    { name: "Venezuela", code: "VE", dial_code: "+58", flag: "🇻🇪" },
    { name: "Vietnã", code: "VN", dial_code: "+84", flag: "🇻🇳" },
    { name: "Zâmbia", code: "ZM", dial_code: "+260", flag: "🇿🇲" },
    { name: "Zimbábue", code: "ZW", dial_code: "+263", flag: "🇿🇼" },
    // Opção para Outro
    { name: "Outro", code: "OT", dial_code: "", flag: "🌍" },
];
